package com.stripe.bbpos.bbdevice;

import com.google.common.base.Ascii;
import com.google.common.primitives.SignedBytes;
import com.stripe.bbpos.bbdevice.BBDeviceController;
import java.util.Hashtable;
import kotlin.io.encoding.Base64;
import okio.Utf8;
import org.kamranzafar.jtar.TarHeader;

/* JADX INFO: loaded from: classes3.dex */
final class ccc024zz {
    static final Hashtable<BBDeviceController.CurrencyCharacter, byte[]> aaa000;
    static final Hashtable<BBDeviceController.CurrencyCharacter, Byte> aaa001;

    static {
        Hashtable<BBDeviceController.CurrencyCharacter, byte[]> hashtable = new Hashtable<>();
        aaa000 = hashtable;
        Hashtable<BBDeviceController.CurrencyCharacter, Byte> hashtable2 = new Hashtable<>();
        aaa001 = hashtable2;
        BBDeviceController.CurrencyCharacter currencyCharacter = BBDeviceController.CurrencyCharacter.A;
        hashtable.put(currencyCharacter, new byte[]{0, 0, -32, Utf8.REPLACEMENT_BYTE, 16, 2, 8, 2, 4, 2, 4, 2, -4, Utf8.REPLACEMENT_BYTE, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter2 = BBDeviceController.CurrencyCharacter.B;
        hashtable.put(currencyCharacter2, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, -124, 32, -124, 32, -124, 32, -124, 32, 120, 31, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter3 = BBDeviceController.CurrencyCharacter.C;
        hashtable.put(currencyCharacter3, new byte[]{0, 0, -16, 15, 8, 16, 4, 32, 4, 32, 4, 32, 8, 16, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter4 = BBDeviceController.CurrencyCharacter.D;
        hashtable.put(currencyCharacter4, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, 4, 32, 4, 32, 4, 32, 4, 32, -8, 31, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter5 = BBDeviceController.CurrencyCharacter.E;
        hashtable.put(currencyCharacter5, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, -124, 32, -124, 32, -124, 32, -124, 32, 4, 32, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter6 = BBDeviceController.CurrencyCharacter.F;
        hashtable.put(currencyCharacter6, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, -124, 0, -124, 0, -124, 0, -124, 0, 4, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter7 = BBDeviceController.CurrencyCharacter.G;
        hashtable.put(currencyCharacter7, new byte[]{0, 0, -8, 31, 4, 32, 4, 32, 4, 34, 4, 34, 8, Ascii.RS, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter8 = BBDeviceController.CurrencyCharacter.H;
        hashtable.put(currencyCharacter8, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, -128, 0, -128, 0, -128, 0, -128, 0, -4, Utf8.REPLACEMENT_BYTE, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter9 = BBDeviceController.CurrencyCharacter.I;
        hashtable.put(currencyCharacter9, new byte[]{0, 0, 4, 32, 4, 32, 4, 32, -4, Utf8.REPLACEMENT_BYTE, 4, 32, 4, 32, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter10 = BBDeviceController.CurrencyCharacter.J;
        hashtable.put(currencyCharacter10, new byte[]{0, 0, 0, Ascii.CAN, 4, 32, 4, 32, 4, 32, 4, 32, -4, 31, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter11 = BBDeviceController.CurrencyCharacter.K;
        hashtable.put(currencyCharacter11, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, -128, 1, 96, 1, 16, 2, 8, 4, 4, 56, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter12 = BBDeviceController.CurrencyCharacter.L;
        hashtable.put(currencyCharacter12, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, 0, 32, 0, 32, 0, 32, 0, 32, 0, 32, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter13 = BBDeviceController.CurrencyCharacter.M;
        hashtable.put(currencyCharacter13, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, 8, 0, 16, 0, 16, 0, 8, 0, -4, Utf8.REPLACEMENT_BYTE, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter14 = BBDeviceController.CurrencyCharacter.N;
        hashtable.put(currencyCharacter14, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, 32, 0, SignedBytes.MAX_POWER_OF_TWO, 0, -128, 0, 0, 1, -4, Utf8.REPLACEMENT_BYTE, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter15 = BBDeviceController.CurrencyCharacter.O;
        hashtable.put(currencyCharacter15, new byte[]{0, 0, -8, 31, 4, 32, 4, 32, 4, 32, 4, 32, -8, 31, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter16 = BBDeviceController.CurrencyCharacter.P;
        hashtable.put(currencyCharacter16, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, -124, 0, -124, 0, -124, 0, -124, 0, 120, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter17 = BBDeviceController.CurrencyCharacter.Q;
        hashtable.put(currencyCharacter17, new byte[]{0, 0, -8, 31, 4, 16, 4, 16, 4, 16, 4, 16, -8, 47, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter18 = BBDeviceController.CurrencyCharacter.R;
        hashtable.put(currencyCharacter18, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, 4, 1, 4, 1, 4, 3, 4, 5, -8, 56, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter19 = BBDeviceController.CurrencyCharacter.S;
        hashtable.put(currencyCharacter19, new byte[]{0, 0, 120, 16, -124, 32, -124, 32, -124, 32, -124, 32, 8, 31, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter20 = BBDeviceController.CurrencyCharacter.T;
        hashtable.put(currencyCharacter20, new byte[]{0, 0, 4, 0, 4, 0, 4, 0, -4, Utf8.REPLACEMENT_BYTE, 4, 0, 4, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter21 = BBDeviceController.CurrencyCharacter.U;
        hashtable.put(currencyCharacter21, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, 0, 32, 0, 32, 0, 32, 0, 32, -4, Utf8.REPLACEMENT_BYTE, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter22 = BBDeviceController.CurrencyCharacter.V;
        hashtable.put(currencyCharacter22, new byte[]{0, 0, -4, 15, 0, 16, 0, 32, 0, 32, 0, 16, -4, 15, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter23 = BBDeviceController.CurrencyCharacter.W;
        hashtable.put(currencyCharacter23, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, 0, 32, 0, 60, 0, 32, 0, 32, -4, 31, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter24 = BBDeviceController.CurrencyCharacter.X;
        hashtable.put(currencyCharacter24, new byte[]{0, 0, 60, 60, SignedBytes.MAX_POWER_OF_TWO, 2, -128, 0, 0, 1, SignedBytes.MAX_POWER_OF_TWO, 2, 60, 60, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter25 = BBDeviceController.CurrencyCharacter.Y;
        hashtable.put(currencyCharacter25, new byte[]{0, 0, 60, 0, SignedBytes.MAX_POWER_OF_TWO, 0, -128, 0, -128, Utf8.REPLACEMENT_BYTE, SignedBytes.MAX_POWER_OF_TWO, 0, 60, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter26 = BBDeviceController.CurrencyCharacter.Z;
        hashtable.put(currencyCharacter26, new byte[]{0, 0, 4, 60, 4, 34, 4, 33, -124, 32, 68, 32, 60, 32, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter27 = BBDeviceController.CurrencyCharacter.RUPEE;
        hashtable.put(currencyCharacter27, new byte[]{0, 0, TarHeader.LF_FIFO, 3, TarHeader.LF_FIFO, 15, -66, Base64.padSymbol, -2, -15, -10, -64, TarHeader.LF_FIFO, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter28 = BBDeviceController.CurrencyCharacter.YEN;
        hashtable.put(currencyCharacter28, new byte[]{0, 0, Ascii.FS, 5, 96, 5, -128, Utf8.REPLACEMENT_BYTE, -128, Utf8.REPLACEMENT_BYTE, 96, 5, Ascii.FS, 5, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter29 = BBDeviceController.CurrencyCharacter.POUND;
        hashtable.put(currencyCharacter29, new byte[]{0, 0, 0, 97, -8, 127, -4, 95, 12, 65, 12, 65, Ascii.CAN, SignedBytes.MAX_POWER_OF_TWO, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter30 = BBDeviceController.CurrencyCharacter.EURO;
        hashtable.put(currencyCharacter30, new byte[]{0, 0, SignedBytes.MAX_POWER_OF_TWO, 1, -8, 31, -4, Utf8.REPLACEMENT_BYTE, 68, 33, 68, 33, 76, TarHeader.LF_NORMAL, Ascii.CAN, Ascii.CAN});
        BBDeviceController.CurrencyCharacter currencyCharacter31 = BBDeviceController.CurrencyCharacter.WON;
        hashtable.put(currencyCharacter31, new byte[]{-128, 2, -8, 15, -128, Ascii.DC2, -8, 15, -128, Ascii.DC2, -8, 15, -128, 2, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter32 = BBDeviceController.CurrencyCharacter.DIRHAM;
        hashtable.put(currencyCharacter32, new byte[]{-2, 103, 0, 0, 0, 16, 0, 0, TarHeader.LF_NORMAL, 8, 96, 8, -64, 8, -128, 7});
        BBDeviceController.CurrencyCharacter currencyCharacter33 = BBDeviceController.CurrencyCharacter.RIYAL;
        hashtable.put(currencyCharacter33, new byte[]{0, 0, 0, 14, 0, Ascii.CAN, 0, 16, 0, 16, 0, Ascii.CAN, -4, 15, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter34 = BBDeviceController.CurrencyCharacter.RIYAL_2;
        hashtable.put(currencyCharacter34, new byte[]{-4, 79, 0, Ascii.CAN, 0, 80, 0, Ascii.CAN, 0, 78, 0, 96, 0, 60, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter35 = BBDeviceController.CurrencyCharacter.DOLLAR;
        hashtable.put(currencyCharacter35, new byte[]{0, 0, 112, 8, -120, 16, -4, Utf8.REPLACEMENT_BYTE, -120, 16, 16, 15, 0, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter36 = BBDeviceController.CurrencyCharacter.SPACE;
        hashtable.put(currencyCharacter36, new byte[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter37 = BBDeviceController.CurrencyCharacter.SLASH_AND_DOT;
        hashtable.put(currencyCharacter37, new byte[]{0, 0, 0, TarHeader.LF_NORMAL, 0, 12, 0, 3, -64, 0, TarHeader.LF_NORMAL, TarHeader.LF_NORMAL, 12, TarHeader.LF_NORMAL, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter38 = BBDeviceController.CurrencyCharacter.DOT;
        hashtable.put(currencyCharacter38, new byte[]{0, 0, 0, TarHeader.LF_NORMAL, 0, TarHeader.LF_NORMAL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter39 = BBDeviceController.CurrencyCharacter.YUAN;
        hashtable.put(currencyCharacter39, new byte[]{0, 0, Ascii.FS, 5, 96, 5, -128, Utf8.REPLACEMENT_BYTE, -128, Utf8.REPLACEMENT_BYTE, 96, 5, Ascii.FS, 5, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter40 = BBDeviceController.CurrencyCharacter.NEW_SHEKEL;
        hashtable.put(currencyCharacter40, new byte[]{0, 0, -8, 31, 8, 0, -24, 31, 8, 16, -8, Ascii.ETB, 0, 16, -8, 31});
        BBDeviceController.CurrencyCharacter currencyCharacter41 = BBDeviceController.CurrencyCharacter.DONG;
        hashtable.put(currencyCharacter41, new byte[]{0, 0, -4, 15, 0, 16, 0, 32, 0, 32, 0, 16, -4, 15, 0, 0, 0, 0, -4, Utf8.REPLACEMENT_BYTE, 32, 0, SignedBytes.MAX_POWER_OF_TWO, 0, -128, 0, 0, 1, -4, Utf8.REPLACEMENT_BYTE, 0, 0, 0, 0, -4, Utf8.REPLACEMENT_BYTE, 4, 32, 4, 32, 4, 32, 4, 32, -8, 31, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter42 = BBDeviceController.CurrencyCharacter.RUPIAH;
        hashtable.put(currencyCharacter42, new byte[]{0, 0, 4, 32, 4, 32, 4, 32, -4, Utf8.REPLACEMENT_BYTE, 4, 32, 4, 32, 0, 0, 0, 0, -4, Utf8.REPLACEMENT_BYTE, 4, 32, 4, 32, 4, 32, 4, 32, -8, 31, 0, 0, 0, 0, -4, Utf8.REPLACEMENT_BYTE, 4, 1, 4, 1, 4, 3, 4, 5, -8, 56, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter43 = BBDeviceController.CurrencyCharacter.SOL;
        hashtable.put(currencyCharacter43, new byte[]{0, 0, 120, 16, -124, 32, -124, 32, -124, 32, -124, 32, 8, 31, 0, 0, 0, 0, 0, TarHeader.LF_NORMAL, 0, 12, 0, 3, -64, 0, TarHeader.LF_NORMAL, TarHeader.LF_NORMAL, 12, TarHeader.LF_NORMAL, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter44 = BBDeviceController.CurrencyCharacter.PESO;
        hashtable.put(currencyCharacter44, new byte[]{0, 0, -4, Utf8.REPLACEMENT_BYTE, -124, 0, -124, 0, -124, 0, -124, 0, 120, 0, 0, 0, 0, 0, -4, Utf8.REPLACEMENT_BYTE, -128, 0, -128, 0, -128, 0, -128, 0, -4, Utf8.REPLACEMENT_BYTE, 0, 0, 0, 0, -4, Utf8.REPLACEMENT_BYTE, -124, 0, -124, 0, -124, 0, -124, 0, 120, 0, 0, 0});
        BBDeviceController.CurrencyCharacter currencyCharacter45 = BBDeviceController.CurrencyCharacter.FORINT;
        hashtable.put(currencyCharacter45, new byte[0]);
        BBDeviceController.CurrencyCharacter currencyCharacter46 = BBDeviceController.CurrencyCharacter.KRONA;
        hashtable.put(currencyCharacter46, new byte[0]);
        BBDeviceController.CurrencyCharacter currencyCharacter47 = BBDeviceController.CurrencyCharacter.KRONE;
        hashtable.put(currencyCharacter47, new byte[0]);
        BBDeviceController.CurrencyCharacter currencyCharacter48 = BBDeviceController.CurrencyCharacter.LEI;
        hashtable.put(currencyCharacter48, new byte[0]);
        BBDeviceController.CurrencyCharacter currencyCharacter49 = BBDeviceController.CurrencyCharacter.REAL;
        hashtable.put(currencyCharacter49, new byte[0]);
        BBDeviceController.CurrencyCharacter currencyCharacter50 = BBDeviceController.CurrencyCharacter.ZLOTY;
        hashtable.put(currencyCharacter50, new byte[0]);
        hashtable2.put(currencyCharacter, (byte) 1);
        hashtable2.put(currencyCharacter2, (byte) 2);
        hashtable2.put(currencyCharacter3, (byte) 3);
        hashtable2.put(currencyCharacter4, (byte) 4);
        hashtable2.put(currencyCharacter5, (byte) 5);
        hashtable2.put(currencyCharacter6, (byte) 6);
        hashtable2.put(currencyCharacter7, (byte) 7);
        hashtable2.put(currencyCharacter8, (byte) 8);
        hashtable2.put(currencyCharacter9, (byte) 9);
        hashtable2.put(currencyCharacter10, (byte) 10);
        hashtable2.put(currencyCharacter11, (byte) 11);
        hashtable2.put(currencyCharacter12, (byte) 12);
        hashtable2.put(currencyCharacter13, (byte) 13);
        hashtable2.put(currencyCharacter14, (byte) 14);
        hashtable2.put(currencyCharacter15, (byte) 15);
        hashtable2.put(currencyCharacter16, (byte) 16);
        hashtable2.put(currencyCharacter17, (byte) 17);
        hashtable2.put(currencyCharacter18, Byte.valueOf(Ascii.DC2));
        hashtable2.put(currencyCharacter19, (byte) 19);
        hashtable2.put(currencyCharacter20, Byte.valueOf(Ascii.DC4));
        hashtable2.put(currencyCharacter21, Byte.valueOf(Ascii.NAK));
        hashtable2.put(currencyCharacter22, Byte.valueOf(Ascii.SYN));
        hashtable2.put(currencyCharacter23, Byte.valueOf(Ascii.ETB));
        hashtable2.put(currencyCharacter24, Byte.valueOf(Ascii.CAN));
        hashtable2.put(currencyCharacter25, Byte.valueOf(Ascii.EM));
        hashtable2.put(currencyCharacter26, Byte.valueOf(Ascii.SUB));
        hashtable2.put(currencyCharacter27, (byte) 31);
        hashtable2.put(currencyCharacter28, (byte) 36);
        hashtable2.put(currencyCharacter29, (byte) 32);
        hashtable2.put(currencyCharacter30, Byte.valueOf(Ascii.RS));
        hashtable2.put(currencyCharacter31, (byte) 35);
        hashtable2.put(currencyCharacter32, Byte.valueOf(Ascii.FS));
        hashtable2.put(currencyCharacter33, (byte) 33);
        hashtable2.put(currencyCharacter34, (byte) 34);
        hashtable2.put(currencyCharacter35, Byte.valueOf(Ascii.GS));
        hashtable2.put(currencyCharacter36, Byte.valueOf(Ascii.ESC));
        hashtable2.put(currencyCharacter37, (byte) 37);
        hashtable2.put(currencyCharacter38, (byte) 38);
        hashtable2.put(currencyCharacter39, (byte) 39);
        hashtable2.put(currencyCharacter40, (byte) 40);
        hashtable2.put(currencyCharacter41, (byte) 41);
        hashtable2.put(currencyCharacter42, (byte) 42);
        hashtable2.put(currencyCharacter43, (byte) 43);
        hashtable2.put(currencyCharacter44, (byte) 44);
        hashtable2.put(currencyCharacter45, (byte) 45);
        hashtable2.put(currencyCharacter46, (byte) 46);
        hashtable2.put(currencyCharacter47, (byte) 46);
        hashtable2.put(currencyCharacter48, (byte) 47);
        hashtable2.put(currencyCharacter49, Byte.valueOf(TarHeader.LF_NORMAL));
        hashtable2.put(currencyCharacter50, Byte.valueOf(TarHeader.LF_LINK));
    }
}
