package org.eclipse.jetty.http;

import org.eclipse.jetty.io.Buffer;
import org.eclipse.jetty.io.BufferCache;

/* JADX INFO: loaded from: classes2.dex */
public class HttpHeaders extends BufferCache {
    public static final String ACCEPT = "Accept";
    public static final Buffer ACCEPT_BUFFER;
    public static final String ACCEPT_CHARSET = "Accept-Charset";
    public static final Buffer ACCEPT_CHARSET_BUFFER;
    public static final int ACCEPT_CHARSET_ORDINAL = 20;
    public static final String ACCEPT_ENCODING = "Accept-Encoding";
    public static final Buffer ACCEPT_ENCODING_BUFFER;
    public static final int ACCEPT_ENCODING_ORDINAL = 21;
    public static final String ACCEPT_LANGUAGE = "Accept-Language";
    public static final Buffer ACCEPT_LANGUAGE_BUFFER;
    public static final int ACCEPT_LANGUAGE_ORDINAL = 22;
    public static final int ACCEPT_ORDINAL = 19;
    public static final String ACCEPT_RANGES = "Accept-Ranges";
    public static final Buffer ACCEPT_RANGES_BUFFER;
    public static final int ACCEPT_RANGES_ORDINAL = 42;
    public static final String AGE = "Age";
    public static final Buffer AGE_BUFFER;
    public static final int AGE_ORDINAL = 43;
    public static final String ALLOW = "Allow";
    public static final Buffer ALLOW_BUFFER;
    public static final int ALLOW_ORDINAL = 9;
    public static final String AUTHORIZATION = "Authorization";
    public static final Buffer AUTHORIZATION_BUFFER;
    public static final int AUTHORIZATION_ORDINAL = 23;
    public static final HttpHeaders CACHE;
    public static final String CACHE_CONTROL = "Cache-Control";
    public static final Buffer CACHE_CONTROL_BUFFER;
    public static final int CACHE_CONTROL_ORDINAL = 57;
    public static final String CONNECTION = "Connection";
    public static final Buffer CONNECTION_BUFFER;
    public static final int CONNECTION_ORDINAL = 1;
    public static final String CONTENT_ENCODING = "Content-Encoding";
    public static final Buffer CONTENT_ENCODING_BUFFER;
    public static final int CONTENT_ENCODING_ORDINAL = 10;
    public static final String CONTENT_LANGUAGE = "Content-Language";
    public static final Buffer CONTENT_LANGUAGE_BUFFER;
    public static final int CONTENT_LANGUAGE_ORDINAL = 11;
    public static final String CONTENT_LENGTH = "Content-Length";
    public static final Buffer CONTENT_LENGTH_BUFFER;
    public static final int CONTENT_LENGTH_ORDINAL = 12;
    public static final String CONTENT_LOCATION = "Content-Location";
    public static final Buffer CONTENT_LOCATION_BUFFER;
    public static final int CONTENT_LOCATION_ORDINAL = 13;
    public static final String CONTENT_MD5 = "Content-MD5";
    public static final Buffer CONTENT_MD5_BUFFER;
    public static final int CONTENT_MD5_ORDINAL = 14;
    public static final String CONTENT_RANGE = "Content-Range";
    public static final Buffer CONTENT_RANGE_BUFFER;
    public static final int CONTENT_RANGE_ORDINAL = 15;
    public static final String CONTENT_TYPE = "Content-Type";
    public static final Buffer CONTENT_TYPE_BUFFER;
    public static final int CONTENT_TYPE_ORDINAL = 16;
    public static final String COOKIE = "Cookie";
    public static final Buffer COOKIE_BUFFER;
    public static final int COOKIE_ORDINAL = 52;
    public static final String DATE = "Date";
    public static final Buffer DATE_BUFFER;
    public static final int DATE_ORDINAL = 2;
    public static final String ETAG = "ETag";
    public static final Buffer ETAG_BUFFER;
    public static final int ETAG_ORDINAL = 44;
    public static final String EXPECT = "Expect";
    public static final Buffer EXPECT_BUFFER;
    public static final int EXPECT_ORDINAL = 24;
    public static final String EXPIRES = "Expires";
    public static final Buffer EXPIRES_BUFFER;
    public static final int EXPIRES_ORDINAL = 17;
    public static final String FORWARDED = "Forwarded";
    public static final Buffer FORWARDED_BUFFER;
    public static final int FORWARDED_ORDINAL = 25;
    public static final String FROM = "From";
    public static final Buffer FROM_BUFFER;
    public static final int FROM_ORDINAL = 26;
    public static final String HOST = "Host";
    public static final Buffer HOST_BUFFER;
    public static final int HOST_ORDINAL = 27;
    public static final String IDENTITY = "identity";
    public static final Buffer IDENTITY_BUFFER;
    public static final int IDENTITY_ORDINAL = 56;
    public static final String IF_MATCH = "If-Match";
    public static final Buffer IF_MATCH_BUFFER;
    public static final int IF_MATCH_ORDINAL = 28;
    public static final String IF_MODIFIED_SINCE = "If-Modified-Since";
    public static final Buffer IF_MODIFIED_SINCE_BUFFER;
    public static final int IF_MODIFIED_SINCE_ORDINAL = 29;
    public static final String IF_NONE_MATCH = "If-None-Match";
    public static final Buffer IF_NONE_MATCH_BUFFER;
    public static final int IF_NONE_MATCH_ORDINAL = 30;
    public static final String IF_RANGE = "If-Range";
    public static final Buffer IF_RANGE_BUFFER;
    public static final int IF_RANGE_ORDINAL = 31;
    public static final String IF_UNMODIFIED_SINCE = "If-Unmodified-Since";
    public static final Buffer IF_UNMODIFIED_SINCE_BUFFER;
    public static final int IF_UNMODIFIED_SINCE_ORDINAL = 32;
    public static final String KEEP_ALIVE = "Keep-Alive";
    public static final Buffer KEEP_ALIVE_BUFFER;
    public static final int KEEP_ALIVE_ORDINAL = 33;
    public static final String LAST_MODIFIED = "Last-Modified";
    public static final Buffer LAST_MODIFIED_BUFFER;
    public static final int LAST_MODIFIED_ORDINAL = 18;
    public static final String LOCATION = "Location";
    public static final Buffer LOCATION_BUFFER;
    public static final int LOCATION_ORDINAL = 45;
    public static final String MAX_FORWARDS = "Max-Forwards";
    public static final Buffer MAX_FORWARDS_BUFFER;
    public static final int MAX_FORWARDS_ORDINAL = 34;
    public static final String MIME_VERSION = "MIME-Version";
    public static final Buffer MIME_VERSION_BUFFER;
    public static final int MIME_VERSION_ORDINAL = 55;
    public static final String NEGOTIATE = "Negotiate";
    public static final String PRAGMA = "Pragma";
    public static final Buffer PRAGMA_BUFFER;
    public static final int PRAGMA_ORDINAL = 3;
    public static final String PROXY_AUTHENTICATE = "Proxy-Authenticate";
    public static final Buffer PROXY_AUTHENTICATE_BUFFER;
    public static final int PROXY_AUTHENTICATE_ORDINAL = 46;
    public static final String PROXY_AUTHORIZATION = "Proxy-Authorization";
    public static final Buffer PROXY_AUTHORIZATION_BUFFER;
    public static final int PROXY_AUTHORIZATION_ORDINAL = 35;
    public static final String PROXY_CONNECTION = "Proxy-Connection";
    public static final Buffer PROXY_CONNECTION_BUFFER;
    public static final int PROXY_CONNECTION_ORDINAL = 58;
    public static final String RANGE = "Range";
    public static final Buffer RANGE_BUFFER;
    public static final int RANGE_ORDINAL = 36;
    public static final String REFERER = "Referer";
    public static final Buffer REFERER_BUFFER;
    public static final int REFERER_ORDINAL = 38;
    public static final String REQUEST_RANGE = "Request-Range";
    public static final Buffer REQUEST_RANGE_BUFFER;
    public static final int REQUEST_RANGE_ORDINAL = 37;
    public static final String RETRY_AFTER = "Retry-After";
    public static final Buffer RETRY_AFTER_BUFFER;
    public static final int RETRY_AFTER_ORDINAL = 47;
    public static final String SERVER = "Server";
    public static final Buffer SERVER_BUFFER;
    public static final int SERVER_ORDINAL = 48;
    public static final String SERVLET_ENGINE = "Servlet-Engine";
    public static final Buffer SERVLET_ENGINE_BUFFER;
    public static final int SERVLET_ENGINE_ORDINAL = 49;
    public static final String SET_COOKIE = "Set-Cookie";
    public static final String SET_COOKIE2 = "Set-Cookie2";
    public static final Buffer SET_COOKIE2_BUFFER;
    public static final int SET_COOKIE2_ORDINAL = 54;
    public static final Buffer SET_COOKIE_BUFFER;
    public static final int SET_COOKIE_ORDINAL = 53;
    public static final String TE = "TE";
    public static final Buffer TE_BUFFER;
    public static final int TE_ORDINAL = 39;
    public static final String TRAILER = "Trailer";
    public static final Buffer TRAILER_BUFFER;
    public static final int TRAILER_ORDINAL = 4;
    public static final String TRANSFER_ENCODING = "Transfer-Encoding";
    public static final Buffer TRANSFER_ENCODING_BUFFER;
    public static final int TRANSFER_ENCODING_ORDINAL = 5;
    public static final String UPGRADE = "Upgrade";
    public static final Buffer UPGRADE_BUFFER;
    public static final int UPGRADE_ORDINAL = 6;
    public static final String USER_AGENT = "User-Agent";
    public static final Buffer USER_AGENT_BUFFER;
    public static final int USER_AGENT_ORDINAL = 40;
    public static final String VARY = "Vary";
    public static final Buffer VARY_BUFFER;
    public static final int VARY_ORDINAL = 50;
    public static final String VIA = "Via";
    public static final Buffer VIA_BUFFER;
    public static final int VIA_ORDINAL = 7;
    public static final String WARNING = "Warning";
    public static final Buffer WARNING_BUFFER;
    public static final int WARNING_ORDINAL = 8;
    public static final String WWW_AUTHENTICATE = "WWW-Authenticate";
    public static final Buffer WWW_AUTHENTICATE_BUFFER;
    public static final int WWW_AUTHENTICATE_ORDINAL = 51;
    public static final String X_FORWARDED_FOR = "X-Forwarded-For";
    public static final Buffer X_FORWARDED_FOR_BUFFER;
    public static final int X_FORWARDED_FOR_ORDINAL = 41;
    public static final String X_FORWARDED_HOST = "X-Forwarded-Host";
    public static final Buffer X_FORWARDED_HOST_BUFFER;
    public static final int X_FORWARDED_HOST_ORDINAL = 61;
    public static final String X_FORWARDED_PROTO = "X-Forwarded-Proto";
    public static final Buffer X_FORWARDED_PROTO_BUFFER;
    public static final int X_FORWARDED_PROTO_ORDINAL = 59;
    public static final String X_FORWARDED_SERVER = "X-Forwarded-Server";
    public static final Buffer X_FORWARDED_SERVER_BUFFER;
    public static final int X_FORWARDED_SERVER_ORDINAL = 60;

    static {
        HttpHeaders httpHeaders = new HttpHeaders();
        CACHE = httpHeaders;
        HOST_BUFFER = httpHeaders.add(HOST, 27);
        ACCEPT_BUFFER = httpHeaders.add(ACCEPT, 19);
        ACCEPT_CHARSET_BUFFER = httpHeaders.add(ACCEPT_CHARSET, 20);
        ACCEPT_ENCODING_BUFFER = httpHeaders.add(ACCEPT_ENCODING, 21);
        ACCEPT_LANGUAGE_BUFFER = httpHeaders.add(ACCEPT_LANGUAGE, 22);
        CONTENT_LENGTH_BUFFER = httpHeaders.add(CONTENT_LENGTH, 12);
        CONNECTION_BUFFER = httpHeaders.add(CONNECTION, 1);
        CACHE_CONTROL_BUFFER = httpHeaders.add(CACHE_CONTROL, 57);
        DATE_BUFFER = httpHeaders.add(DATE, 2);
        PRAGMA_BUFFER = httpHeaders.add(PRAGMA, 3);
        TRAILER_BUFFER = httpHeaders.add(TRAILER, 4);
        TRANSFER_ENCODING_BUFFER = httpHeaders.add(TRANSFER_ENCODING, 5);
        UPGRADE_BUFFER = httpHeaders.add("Upgrade", 6);
        VIA_BUFFER = httpHeaders.add(VIA, 7);
        WARNING_BUFFER = httpHeaders.add(WARNING, 8);
        ALLOW_BUFFER = httpHeaders.add(ALLOW, 9);
        CONTENT_ENCODING_BUFFER = httpHeaders.add(CONTENT_ENCODING, 10);
        CONTENT_LANGUAGE_BUFFER = httpHeaders.add(CONTENT_LANGUAGE, 11);
        CONTENT_LOCATION_BUFFER = httpHeaders.add(CONTENT_LOCATION, 13);
        CONTENT_MD5_BUFFER = httpHeaders.add(CONTENT_MD5, 14);
        CONTENT_RANGE_BUFFER = httpHeaders.add(CONTENT_RANGE, 15);
        CONTENT_TYPE_BUFFER = httpHeaders.add(CONTENT_TYPE, 16);
        EXPIRES_BUFFER = httpHeaders.add(EXPIRES, 17);
        LAST_MODIFIED_BUFFER = httpHeaders.add(LAST_MODIFIED, 18);
        AUTHORIZATION_BUFFER = httpHeaders.add(AUTHORIZATION, 23);
        EXPECT_BUFFER = httpHeaders.add(EXPECT, 24);
        FORWARDED_BUFFER = httpHeaders.add(FORWARDED, 25);
        FROM_BUFFER = httpHeaders.add(FROM, 26);
        IF_MATCH_BUFFER = httpHeaders.add(IF_MATCH, 28);
        IF_MODIFIED_SINCE_BUFFER = httpHeaders.add(IF_MODIFIED_SINCE, 29);
        IF_NONE_MATCH_BUFFER = httpHeaders.add(IF_NONE_MATCH, 30);
        IF_RANGE_BUFFER = httpHeaders.add(IF_RANGE, 31);
        IF_UNMODIFIED_SINCE_BUFFER = httpHeaders.add(IF_UNMODIFIED_SINCE, 32);
        KEEP_ALIVE_BUFFER = httpHeaders.add(KEEP_ALIVE, 33);
        MAX_FORWARDS_BUFFER = httpHeaders.add(MAX_FORWARDS, 34);
        PROXY_AUTHORIZATION_BUFFER = httpHeaders.add(PROXY_AUTHORIZATION, 35);
        RANGE_BUFFER = httpHeaders.add(RANGE, 36);
        REQUEST_RANGE_BUFFER = httpHeaders.add(REQUEST_RANGE, 37);
        REFERER_BUFFER = httpHeaders.add(REFERER, 38);
        TE_BUFFER = httpHeaders.add("TE", 39);
        USER_AGENT_BUFFER = httpHeaders.add(USER_AGENT, 40);
        X_FORWARDED_FOR_BUFFER = httpHeaders.add(X_FORWARDED_FOR, 41);
        X_FORWARDED_PROTO_BUFFER = httpHeaders.add(X_FORWARDED_PROTO, 59);
        X_FORWARDED_SERVER_BUFFER = httpHeaders.add(X_FORWARDED_SERVER, 60);
        X_FORWARDED_HOST_BUFFER = httpHeaders.add(X_FORWARDED_HOST, 61);
        ACCEPT_RANGES_BUFFER = httpHeaders.add(ACCEPT_RANGES, 42);
        AGE_BUFFER = httpHeaders.add(AGE, 43);
        ETAG_BUFFER = httpHeaders.add(ETAG, 44);
        LOCATION_BUFFER = httpHeaders.add(LOCATION, 45);
        PROXY_AUTHENTICATE_BUFFER = httpHeaders.add(PROXY_AUTHENTICATE, 46);
        RETRY_AFTER_BUFFER = httpHeaders.add(RETRY_AFTER, 47);
        SERVER_BUFFER = httpHeaders.add(SERVER, 48);
        SERVLET_ENGINE_BUFFER = httpHeaders.add(SERVLET_ENGINE, 49);
        VARY_BUFFER = httpHeaders.add(VARY, 50);
        WWW_AUTHENTICATE_BUFFER = httpHeaders.add(WWW_AUTHENTICATE, 51);
        COOKIE_BUFFER = httpHeaders.add(COOKIE, 52);
        SET_COOKIE_BUFFER = httpHeaders.add(SET_COOKIE, 53);
        SET_COOKIE2_BUFFER = httpHeaders.add(SET_COOKIE2, 54);
        MIME_VERSION_BUFFER = httpHeaders.add(MIME_VERSION, 55);
        IDENTITY_BUFFER = httpHeaders.add("identity", 56);
        PROXY_CONNECTION_BUFFER = httpHeaders.add(PROXY_CONNECTION, 58);
    }
}
